version: '3'

services:
  db:
    image: postgres:alpine3.17
    container_name: tcg_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432